import { defineConfig } from 'orval';

export default defineConfig({
	graphbit: {
		input: 'https://developer.themoviedb.org/openapi/tmdb-api.json',
		output: {
			client: 'react-query',
			mode: 'tags-split',
			target: './src/generated/tmdb',
			httpClient: 'axios',
			override: {
				query: {
					useQuery: true,
					useMutation: true,
					useSuspenseQuery: true,
				},
				mutator: {
					path: './src/services/tmdb-api-client.ts',
					name: 'customInstance',
				},
				header: (info) => [
					`Generated by orval 🍺`,
					`Do not edit manually.`,
					...(info.title ? [info.title] : []),
					...(info.description ? [info.description] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
					'eslint-disable',
				],
			},
		},
	},
});
